### ISSUE TITLE
Implement Quests

### ISSUE THREAD

**Issue by derpfacedirk** [derpfacedirk/Goldiriath#1]
Example Quests: https://github.com/Goldiriath/Goldiriath/wiki/Quests

Quest Implementation (_branch: **quests**_):
- [x] Implement basic quest loading and parsing
- [x] Implement quest playerdata saving and loading
- [x] Implement global config
  - [x] Requirements
  - [x] Rewards
- [x] Quest dialog?
- [x] Implement quest requirements
  - [x] Inverse Requirements
  - [x] Health
  - [x] Money
  - [x] Mana
  - [x] Level
  - [x] Quest
  - [x] Skill
  - [x] Flag
- [x] Implement quest triggers
  - [x] Location
  - [x] Item obtain
    - [x] Custom items
  - [x] NPC Click
- [x] Implement quest logic
- [x] Implement quest stages
  - [x] Actions
  - [x] Triggers
  - [x] Complete/cancel stages
- [x] Implement scriptable actions #25.
- [x] Implement quest admin command

**Comment by JeromSar** [comment]
@derpfacedirk I suggest storing quests in a config-per-quest way. Perhaps have a subfolder under the plugin configuration folder just for quests. Here's my take on how quests could be stored:

[_snip snip_] **Moved to wiki**

**Comment by Hakhaktak** [comment]
I agree with Jerom, and I've made something myself. We may can combine both.


quests:
  questID: #ID of the quest, can be identical to the questname
    questname: #name of the certain quest
    questgiver: #npcname/npcID
    reward: #reward in golden nuggets/money, XP and items. (something else can be added later on)
      nuggets: #amount of nuggets/money to be given
      xp: #amount of XP given
      items:
        itemname: #name for item in quest, doesnt need the real ingame name, just for coding purposes.
          itemID: #ID of the given item(s)
          itemamount: #how many items should be given?
        itemname: #name for item in quest, doesnt need the real ingame name, just for coding purposes.
          itemID: #ID of the given item(s)
          itemamount: #how many items should be given?
        #and so on
    questcommands:
      #what should the player do, every - is followed by an action. There can be placed as many questcommands as needed.
      -
      -
    queststory:
      #place background story of the quest and additional information

**Comment by Hakhaktak** [comment]
I agree with Jerom, and I've made something myself. We may can combine both.

``` yaml
quests:
  questID: #ID of the quest, can be identical to the questname
    questname: #name of the certain quest
    questgiver: #npcname/npcID
    reward: #reward in golden nuggets/money, XP and items. (something else can be added later on)
      nuggets: #amount of nuggets/money to be given
      xp: #amount of XP given
      items:
        itemname: #name for item in quest, doesnt need the real ingame name, just for coding purposes.
          itemID: #ID of the given item(s)
          itemamount: #how many items should be given?
        itemname: #name for item in quest, doesnt need the real ingame name, just for coding purposes.
          itemID: #ID of the given item(s)
          itemamount: #how many items should be given?
        #and so on
    questcommands:
      #what should the player do, every - is followed by an action. There can be placed as many questcommands as needed.
      -
      -
    queststory:
      #place background story of the quest and additional information
```
